apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadboad-web
  name: loadboard-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadboard-web
  strategy: {}
  template:
    metadata:
      labels:
        app: loadboard-web
    spec:
      containers:
      - image: $IMAGE
        name: loadboard-web
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadboard-web
  name: loadboard-web
spec:
  selector:
    app: loadboard-web
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30036
