apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadboad-web
  name: loadboard-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadboard-web
  strategy: {}
  template:
    metadata:
      labels:
        app: loadboard-web
    spec:
      containers:
      - image: $IMAGE
        name: loadboard-web
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadboard-web
  name: loadboard-web
spec:
  selector:
    app: loadboard-web
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: loadboard-poc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: loadboard-web
              servicePort: 8080
