apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadboad-web
  name: loadboard-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loadboard-web
  strategy: {}
  template:
    metadata:
      labels:
        app: loadboard-web
    spec:
      containers:
      - image: 192.100.0.24:32000/loadboard-web:$IMAGE_TAG
        name: java-basics
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadboard-web
  name: loadboard-web
spec:
  selector:
    app: loadboard-web
  type: NodePort
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30036
